version: "3.2"
services:
  customer-service:
    container_name: customer-service
    image: customer-service
    build:
      context: '.'
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/var/app
      - ./.docker/start.sh:/usr/local/bin/start.sh
    depends_on:
      - customer-database
  customer-database:
    container_name: customer-database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - customer-data:/var/lib/mysql
  customer-adminer:
    container_name: customer-adminer
    image: adminer
    restart: always
    environment: 
        ADMINER_DEFAULT_SERVER: customer-database
    ports:
      - ${ADMINER_PORT}:8080
volumes:
  customer-data:
